#First define the first two numbers in the function input parameter.
def fibonacci(FirstNumber,SecondNumber):
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    '''
    #Start the Fibonacci sequence and get a variable to store the final Fibonacci value which is less than 4 million.
    #Initializing SumofEvenNumbers(Variable that stores sum of the even numbers) as 2 since we have to consider all the values to get correct sum.
    FinalValue = 0
    SumofEvenNumbers = 2
    #Create a loop which does loop till the final Finonacci value is less than 4 million.
    while(FinalValue < 4000000):
        #Swap values between variables.
        FinalValue = FirstNumber + SecondNumber
        FirstNumber = SecondNumber
        SecondNumber = FinalValue
        
        #Condition to filter the even numbers.
        if (FinalValue % 2 == 0 and FinalValue < 4000000):
            SumofEvenNumbers +=FinalValue
            

    return SumofEvenNumbers 


print(fibonacci(1,2))

  



    

